.\" Copyright (c) 2020-2026, Matthew Wilson and Synesis Information Systems
.\"
.TH LSTRIP 1 "August 2026" "lstrip 0.1.1" "User Commands"
.SH NAME
lstrip \- remove leading whitespace from input lines
.SH SYNOPSIS
.B lstrip
[\fIOPTIONS\fR]
[\fIINPUT\fR [\fIOUTPUT\fR]]
.SH DESCRIPTION
.B lstrip
removes leading whitespace from each input line. Input and output default to
standard input and standard output when omitted or specified as
.BR \- .
.SH OPTIONS
.B lstrip
accepts the following options:
.TP
.B \-\-help
Display help and exit.
.TP
.B \-\-version
Display version information and exit.
.SH SEE ALSO
.BR chomp (1),
.BR rstrip (1)
.SH REPORTING BUGS
Report defects and feature requests at
https://github.com/sistools/lstrip.
.SH AUTHOR
Matthew Wilson and Synesis Information Systems
.br
Copyright (c) 2020\-2026, Matthew Wilson and Synesis Information Systems
